### PR TITLE
Create TemplateGoldorak.kicad_wks

### PR DESCRIPTION
**Pull request by alfarobase**

### CODE REVIEW

**Review by kmikaz51 — CHANGES_REQUESTED** [review]
Logo pas à jour

**Comment by alfarobase** [comment]
> Contributor

done

**Comment by kmikaz51** [comment]
> Logo pas à jour

done

**Review by kmikaz51 — COMMENTED** [review]
Are you sure about the logo position ?

**Comment by kmikaz51** [comment]
> Are you sure about the logo position ?

Ok

**Comment by kmikaz51** [comment]
Useless

**Pull request closed without merging**
